apiVersion: v1
kind: Pod
metadata:
  name: nginx-{{ .Values.memory }}
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: {{ printf "%dMi" .Values.memory | quote }}